FUNPASS_PATH = File.join(Dir.home, '.funpass')
SECRET_PATH = File.join(FUNPASS_PATH, 'secret')
SECRET_KEY_LENGTH_IN_BITS = 4096
SECRET_KEY_MODULUS = 2 ** SECRET_KEY_LENGTH_IN_BITS
PASSWORD_BASE = 62
PASSWORD_LENGTH = 30
